// pages/api/export/md.ts
// POST — Export a document as a raw Markdown (.md) file.
//
// Body: { markdownContent: string, documentTitle: string, employeeId: string }
// Returns: .md file as text/markdown download

import type { NextApiRequest, NextApiResponse } from 'next'
import { withAuth } from '@/lib/api-middleware'
import { adminDb } from '@/lib/firebase/admin'
import { createAuditLog } from '@/lib/audit/logger'
import { generateFileName } from '@/lib/export/file-naming'
import { format } from 'date-fns'

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed.' })
  }

  return await withAuth(req, res, async (uid, email): Promise<void> => {
    try {
      const { markdownContent, documentTitle, employeeId } = req.body as {
        markdownContent: string
        documentTitle: string
        employeeId: string
      }

      if (!markdownContent || !documentTitle || !employeeId) {
        return res.status(400).json({ error: 'Missing required fields.' })
      }

      // ── 1. Fetch company name to prepend a front-matter block ────────
      const settingsDoc = await adminDb.collection('settings').doc('company').get()
      const settings = settingsDoc.exists ? (settingsDoc.data() as Record<string, string>) : {}
      const companyName = settings.companyName || 'AirBuddy Aerospace Pvt. Ltd.'

      const dateStr = format(new Date(), 'dd/MM/yyyy')

      // ── 2. Build the .md file content with a YAML-style front matter ──
      const fullContent = [
        '---',
        `title: "${documentTitle}"`,
        `company: "${companyName}"`,
        `employee_id: "${employeeId}"`,
        `generated_on: "${dateStr}"`,
        `generated_by: "AirBuddy HR Platform"`,
        '---',
        '',
        markdownContent,
        '',
        '---',
        '',
        `*Generated by AirBuddy HR Platform on ${dateStr}*`,
      ].join('\n')

      const mdBuffer = Buffer.from(fullContent, 'utf-8')

      // ── 3. Audit log ─────────────────────────────────────────────────
      await createAuditLog({
        action: 'DOCUMENT_EXPORT',
        entityType: 'document',
        entityId: employeeId, // no documentId in this endpoint — use employeeId
        performedBy: uid,
        performedByEmail: email,
        metadata: {
          employeeId,
          format: 'md',
          documentTitle,
        },
      })

      // ── 4. Stream .md file to client ─────────────────────────────────
      const filename = generateFileName(employeeId, documentTitle, 'md')

      res.setHeader('Content-Type', 'text/markdown; charset=utf-8')
      res.setHeader('Content-Disposition', `attachment; filename="${encodeURIComponent(filename)}"`)
      res.setHeader('Content-Length', mdBuffer.length)
      res.status(200).end(mdBuffer)
    } catch (err) {
      console.error('[POST /api/export/md]', err)
      res.status(500).json({ error: 'Failed to export Markdown.' })
    }
  })
}
